# Generated by Django 3.2.4 on 2023-08-10 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_user_id_likepost_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='no_of_links',
            new_name='no_of_likes',
        ),
    ]
